### PR TITLE
Add interface for be able to launch different queues for plots

### PR DESCRIPTION
**Pull request by jespino**
This requires the changes in the PR Chia-Network/chia-blockchain#1168

### CODE REVIEW

**Review by mariano54 — APPROVED** [review]
I have not tested it, but I assume you have? It looks good to me!

**Comment by jespino** [comment]
I tested it, not all the corner cases, but at least adding two queues, (they run in parallel), removing things queue or running queue doesn't affects the other queue.

**Comment by jespino** [comment]
@hoffmang9 this requires the corresponding changes in the chia-blockchain repo.

**Comment by hoffmang9** [comment]
Yep. Am just slow on Saturday AM.

**Pull request merged**
