### PR TITLE
Update messages.po (german)

### PR DESCRIPTION
**Pull request by Dravenex**
I hope you like it. I edited it first on main, sorry for that.

### CODE REVIEW

**Comment by seeden** [comment]
Hi @Dravenex. 
First of all, thank you for your work.
I am sorry but we are not accepting translations via GitHub PR. 
If you want to improve translations you need to add your translations here https://crowdin.com/project/chia-blockchain.
The reason is that we have automatic PR from Crowdin and we are not able to do it in the opposite way.

**Comment by Dravenex** [comment]
Hello Zlatko,

thanks for your information. I will edit the messages.po at crowdin then. :)

I just clicked in the chia Interface on „help translate“ which directly sent me to GitHub. 

Best regards 
André Bender

**Comment by hoffmang9** [comment]
We need to update the README. My apologies.

**Comment by Dravenex** [comment]
Hello Mr. Hoffman,

 

I just finished the german translation and it has now 100% completion. Unfortunately I can’t see where my translation will be in the GUI. So I might change some translations afterwards.

 

When is it possible to test the translation in the GUI?

 

Best regards,

André (Dravenex)

 

Von: Gene Hoffman ***@***.***> 
Gesendet: Samstag, 20. März 2021 18:02
An: Chia-Network/chia-blockchain-gui ***@***.***>
Cc: Dravenex ***@***.***>; Mention ***@***.***>
Betreff: Re: [Chia-Network/chia-blockchain-gui] Update messages.po (german) (#182)

 

We need to update the README. My apologies.

**Comment by hoffmang9** [comment]
Unfortunately there isn't an easy way to see the results until we include it in a release. That will probably be next week for a testnet release.

**Pull request closed without merging**
