### PR TITLE
fixed adding cats

### PR DESCRIPTION
**Pull request by seeden**
used own local storage hook because window listener is not working in electron for storage event
invalidate api-react cache
fixed wallet name and used meta name

### CODE REVIEW

**Comment by paninaro** [comment]
Thanks @seeden, this is definitely an improvement. There's still one scenario that doesn't work as I'd expect.

If I type in the name for a wallet that hasn't been created yet, and click the toggle button, the wallet gets added with the specified name, but the toggle remains in the off position.

**Comment by seeden** [comment]
I pushed changes related to this issue.

**Review by paninaro — APPROVED** [review]
Tested latest changes. LGTM

**Comment by CyrilOllier** [comment]
Hello, I hope I am in the right place to post my question, is there a way to reduce or remove the size of the db to 161 GB this takes a bit of space that I have been plotting for +1 years to pass and I recently updated my version
Thank you for your feedback,
Warmly
Capturechia

**Comment by paninaro** [comment]
@CyrilOllier you can update to the V2 database format by following the instructions below. That should reduce the DB size.

https://github.com/Chia-Network/chia-blockchain/wiki/FAQ#what-is-the-new-database

If you have additional questions, Keybase would be a great place to ask for help: https://keybase.io/team/chia_network.public

Hope that helps!

**Pull request merged**
