### PR TITLE
Remove not usable for farming plot sizes from the GUI

### LINKED ISSUE #129: Don't allow (or have a large warning for) small plots
Minimum k is 32 for mainnet, but the GUI still allows smaller plots, and only shows a small warning. This can confuse new users.

### PR DESCRIPTION
**Pull request by jespino**
Fixes #129

### CODE REVIEW

**Comment by jespino** [comment]
@seeden this was assigned to you, but I fixed it, I hope it is ok :)

**Review by mariano54 — APPROVED** [review]
thank you!

**Comment by hoffmang9** [comment]
We need to leave 25 in for even normal end user testing but the rest need to go. Choosing 25 needs an "are you sure?" Or similar

**Comment by jespino** [comment]
@hoffmang9 I can take care of that.

**Comment by seeden** [comment]
I am closing it. I did it in a little bit different way here https://github.com/Chia-Network/chia-blockchain-gui/pull/144

**Pull request closed without merging**
