### PR TITLE
Add dexie.space to offer share dialog

### PR DESCRIPTION
**Pull request by denisu**
https://dexie.space is a new Chia offer file exchange. This pull request adds a button for dexie to the offer share dialog.

screenshot

### CODE REVIEW

**Comment by zakhikhan** [comment]
Would love to see Dexie in the Chia GUI. It is the DEX I use most often and I think it has the best UX

**Comment by ojura** [comment]
@denisu would love to see this merged. Could you ping the devs on Keybase to show this PR some love?

**Comment by chia-ng-mai** [comment]
Should this be closed as #766 has been merged?

**Comment by denisu** [comment]
Yes, I will close this one. Great to see it merged! 🙂

**Pull request closed without merging**
