### PR TITLE
Add more information for remote daemon setup

### PR DESCRIPTION
**Pull request by yousefamar**
This is based on @dkackman's incredibly helpful troubleshooting and hopefully helps others in the future

### CODE REVIEW

**Comment by hoffmang9** [comment]
Could you instead update the wiki and make this PR just point to it? https://github.com/Chia-Network/chia-blockchain/wiki/Connecting-the-UI-to-a-remote-daemon

**Comment by dkackman** [comment]
Also. I did add some experience based troubleshooting tips to that wiki page. They may accomplish this same end.

**Review by atyhieu — APPROVED** [review]

**Comment by dkackman** [comment]
I think this one can be closed

**Comment by jack60612** [comment]
@yousefamar i dont think this is still needed. 
Would you mind closing it.

**Pull request closed without merging**
