### PR TITLE
Added RAM plot option for bladebit2

### PR DESCRIPTION
**Pull request by ChiaMineJP**
# Changelog
## Deprecated
- Dropped support for bladebit < 2
## Changed
- Now users can choose RAM plot and Disk plot with bladebit

## Note
This PR should be merged after
https://github.com/Chia-Network/chia-blockchain/pull/13833
is merged.

### CODE REVIEW

**Comment by ChiaMineJP** [comment]
Relevant PR: https://github.com/Chia-Network/chia-blockchain/pull/13833

**Comment by ChiaMineJP** [comment]
image

**Comment by ChiaMineJP** [comment]
As we discussed, I'll drop support for old bladebit1 and I'll add commits for it.

**Review by paninaro — COMMENTED** [review]
lgtm

**Review by paninaro — APPROVED** [review]
lgtm

**Pull request merged**
